import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@services/redux/provider";
import ThemeProvider from "@infrastructure/theme/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <StoreProvider>
        <html lang="en">
          <body className={inter.className}>
            <nav>NAV</nav>
            {children}
          </body>
        </html>
      </StoreProvider>
    </ThemeProvider>
  );
}
